name: daily_data_pipeline

on:
  schedule:
    - cron: "0 3 * * *"  # runs daily at 3 AM UTC
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      CHICAGO_API_TOKEN: ${{ secrets.CHICAGO_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore Google Sheets credentials
        run: |
          echo "$GOOGLE_CREDENTIALS" | base64 --decode > credentials.json

      - name: Fetch and load Chicago data
        run: python data/load_data.py
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
          CHICAGO_API_TOKEN: ${{ secrets.CHICAGO_API_TOKEN }}

      - name: Run Google ratings update
        run: python data/update_google_ratings.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: Sync to Google Sheets
        run: python data/sync_to_sheets.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: Clean up credentials
        run: rm credentials.json
